### PR TITLE
PROVO alignment to BFO

### PR DESCRIPTION
**Pull request by tmprd**
- This shows how the `prov-o-edit.ttl` file (a copy of the original) has been changed
- To compare, here is how ROBOT shows the difference in changes (eventually this output will be generated on every commit):
```
java -jar build/lib/robot.jar diff --left PROV/prov-o-edit.ttl --right PROV/prov-o.ttl --labels true

14 axioms in left ontology but not in right ontology:
- Declaration(NamedIndividual(<http://www.w3.org/ns/prov-o-20130312>))
- Declaration(NamedIndividual(<http://www.w3.org/ns/prov-o>))
- Declaration(NamedIndividual(<prov:>))
- EquivalentClasses(<BFO:0000002>[continuant] <prov:Entity>[Entity])
- EquivalentClasses(<BFO:0000035>[process boundary] <prov:InstantaneousEvent>[InstantaneousEvent])
- Import(<http://purl.obolibrary.org/obo/bfo/2.0/bfo.owl>)
- ObjectPropertyAssertion(<prov:specializationOf>[specializationOf] <prov:> <http://www.w3.org/ns/prov-o>)
- ObjectPropertyAssertion(<prov:wasRevisionOf>[wasRevisionOf] <prov:> <http://www.w3.org/ns/prov-o-20130312>)
- OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>) VersionIRI(<http://www.w3.org/ns/prov-o-20130430>))
- SubClassOf(<prov:Activity>[Activity] <BFO:0000015>[process])
- SubClassOf(<prov:Agent>[Agent] <BFO:0000040>[material entity])
- SubClassOf(<prov:Influence>[Influence] <BFO:0000016>[disposition])
- SubClassOf(<prov:Location>[Location] <BFO:0000002>[continuant])
- SubClassOf(<prov:Role>[Role] <BFO:0000023>[role])

3 axioms in right ontology but not in left ontology:
+ ObjectPropertyAssertion(<prov:specializationOf>[specializationOf] <http://www.w3.org/ns/prov-o#> <http://www.w3.org/ns/prov-o>)
+ ObjectPropertyAssertion(<prov:wasRevisionOf>[wasRevisionOf] <http://www.w3.org/ns/prov-o#> <http://www.w3.org/ns/prov-o-20130312>)
+ OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>) VersionIRI(<null>))
```
- Currently, this is showing a failed automated test (some classes are unsatisfiable) https://github.com/BFO-Mappings/BFO-Mappings/actions/runs/4246169485/jobs/7382628319

### CODE REVIEW

**Comment by SydCo99** [comment]
Thanks for setting this up and running it, Tim. This will be incredibly useful moving forward. I notice the 5 unsatisfiable classes are the PROV terms Usage, Generation, End, Invalidation and Start. Since we're changing a lot of the process level PROV terms, mapping those terms correctly onto the BFO hierarchy while retaining their intended PROV meaning will be something to look at this Friday. 

In terms of the content of the additions (based on the differences ROBOT picked up on), it looks good to me. I am curious why we put PROV:agent as a subclass of material entity, have we decided that this is okay given the material and/or immaterial nature of the "software agent" term?

**Comment by tmprd** [comment]
> In terms of the content of the additions (based on the differences ROBOT picked up on), it looks good to me. I am curious why we put PROV:agent as a subclass of material entity, have we decided that this is okay given the material and/or immaterial nature of the "software agent" term?

Good question. I think a few people said we should treat software agents in this case as the material aspect (realization?) of the immaterial aspect of software. I can see how that would work but we should definitely talk it over some more, and, if we do go with material entity, adding something to the ontology that clarifies its relationship to immaterial software.

**Comment by SydCo99** [comment]
That makes sense to me, as the realization of software running has to be contained in a material entity. And, this doesn't necessarily rule out cases where the software runs, and fails at its task. I do like the idea of adding a note for clarity, that will probably be important. 

Perhaps a more complicated case will arise in software development, when the relevant code exists solely in cloud storage and isn't actually being run, but instead developed by a team. But that isn't really an agent role anyway, that would be the PROV entity, which can be material or immaterial -- lets iron out these differences, I'll bring it up Friday.

**Comment by tmprd** [comment]
Updates so far
```shell
java -jar build/lib/robot.jar diff --left PROV/prov-o-edit.ttl --right PROV/prov-o.ttl --labels true

46 axioms in left ontology but not in right ontology:
- Annotation(<dc11:contributor> "Alec Sculley")
- Annotation(<dc11:contributor> "Ali Hasanzadeh")
- Annotation(<dc11:contributor> "Austin Liebers")
- Annotation(<dc11:contributor> "Giacomo De Colle")
- Annotation(<dc11:contributor> "Peihong Karl Xie")
- Annotation(<dc11:contributor> "Sydney Cohen")
- Annotation(<dc11:contributor> "Tim Prudhomme")
- AnnotationAssertion(<IAO:0000115>[definition] <prov:Activity>[Activity] "An activity is a process that has some participant that acts upon some continuant.") 
- AnnotationAssertion(<IAO:0000115>[definition] <prov:AgentRole> "An agent role is a role borne by some material entity, that, if realized, is realized in an activity taking place")
- AnnotationAssertion(<IAO:0000115>[definition] <prov:Influence>[Influence] "Influence is a prov:activity that has an effect on the character, development, or behavior of another entity, activity, or agent")
- AnnotationAssertion(<IAO:0000116>[obo:IAO_0000116] <prov:Role>[Role] "Work in progress")
- AnnotationAssertion(<http://www.ontologyrepository.com/CommonCoreOntologies/definition> <http://www.ontologyrepository.com/CommonCoreOntologies/affects>[affects] "p affects c iff p is an instance of a Process and c is an instance of a Continuant, such that p influences c in some manner, most often by producing a change in c."@en)
- AnnotationAssertion(<http://www.ontologyrepository.com/CommonCoreOntologies/is_curated_in_ontology> <http://www.ontologyrepository.com/CommonCoreOntologies/affects>[affects] "http://www.ontologyrepository.com/CommonCoreOntologies/Mid/ExtendedRelationOntology"^^xsd:anyURI)
- AnnotationAssertion(<owl:deprecated> <prov:InstantaneousEvent>[InstantaneousEvent] "true"^^xsd:boolean)
- AnnotationAssertion(<rdfs:label> <http://www.ontologyrepository.com/CommonCoreOntologies/affects>[affects] "affects"@en)
- Declaration(AnnotationProperty(<http://www.ontologyrepository.com/CommonCoreOntologies/definition>))
- Declaration(AnnotationProperty(<http://www.ontologyrepository.com/CommonCoreOntologies/is_curated_in_ontology>))
- Declaration(Class(<BFO:0000002>[continuant]))
- Declaration(Class(<BFO:0000015>[process]))
- Declaration(Class(<prov:AgentRole>))
- Declaration(NamedIndividual(<http://www.w3.org/ns/prov-o-20130312>))
- SubClassOf(<prov:Agent>[Agent] ObjectSomeValuesFrom(<RO:0000053>[has characteristic] <prov:Role>[Role]))
- SubClassOf(<prov:Agent>[Agent] ObjectSomeValuesFrom(<RO:0000087>[has role] <prov:AgentRole>))
- SubClassOf(<prov:AgentRole> <BFO:0000023>[role])
- SubClassOf(<prov:Influence>[Influence] <prov:Activity>[Activity])
- SubClassOf(<prov:InstantaneousEvent>[InstantaneousEvent] <BFO:0000035>[process boundary])
- SubClassOf(<prov:Location>[Location] <BFO:0000029>[site])
- SubClassOf(<prov:Role>[Role] <BFO:0000034>[function])
- SubObjectPropertyOf(<http://www.ontologyrepository.com/CommonCoreOntologies/affects>[affects] <RO:0000057>[has participant])

8 axioms in right ontology but not in left ontology:
+ ObjectPropertyAssertion(<prov:specializationOf>[specializationOf] <http://www.w3.org/ns/prov-o#> <http://www.w3.org/ns/prov-o>)
+ ObjectPropertyAssertion(<prov:wasRevisionOf>[wasRevisionOf] <http://www.w3.org/ns/prov-o#> <http://www.w3.org/ns/prov-o-20130312>)
+ OntologyID(OntologyIRI(<http://www.w3.org/ns/prov#>) VersionIRI(<null>))
+ SubClassOf(<prov:End>[End] <prov:InstantaneousEvent>[InstantaneousEvent])
+ SubClassOf(<prov:Generation>[Generation] <prov:InstantaneousEvent>[InstantaneousEvent])
+ SubClassOf(<prov:Invalidation>[Invalidation] <prov:InstantaneousEvent>[InstantaneousEvent])
+ SubClassOf(<prov:Start>[Start] <prov:InstantaneousEvent>[InstantaneousEvent])
+ SubClassOf(<prov:Usage>[Usage] <prov:InstantaneousEvent>[InstantaneousEvent])
```

**Pull request closed without merging**
