### PR TITLE
Only import MIREOT terms from RO

### PR DESCRIPTION
**Pull request by tmprd**
* Importing all of RO makes testing with a reasoner slower if not impossible
* This solution imports only the RO terms we need using OntoFox

### CODE REVIEW

**Comment by jonathanvajda** [comment]
Apologies, but why RO, and not CCO's extended relations ontology? Does the same issue occur with ERO?

**Comment by tmprd** [comment]
Good question. I think we wanted to offer interoperability with RO, but I know there's a lot of demand for aligning to CCO. In any case we should probably just make a PROV-BFO only extension, and separate extensions for PROV-CCO and (I guess) PROV-RO.

As for the slowness, it only occurs with the HermiT reasoner, so maybe testing with ELK might be enough (for PROV-RO)...

**Comment by johnbeve** [comment]
I would encourage focusing on ERO. The most pressing user base is from the CCO community and that base is growing significantly.

**Comment by jonathanvajda** [comment]
I am having long loading times for HermiT on other projects as well.

In addition to what Beverley said, ERO has everything you need (it was a fork of RO) and preserves BFO's design pattern for the relation 'bearer_of' (OBO changed the domain of the relation rather than deprecating or creating a new IRI for that change)

**Comment by johnbeve** [comment]
@jonathanvajda That's "Dr. Your Honor Beverley Sir", sir. 

Jk, that's my father. 

Jk<sup>2</sup>, no it's not. 

Jk<sup>3</sup>, I don't know my father so it might be.

**Comment by tmprd** [comment]
Ok I'm thinking we make a PROV-BFO only extension, and then a PROV-CCO extension that imports PROV-BFO. The reason for separating them is to keep them independent, and the reason for importing one into the other is keeping them consistent. PROV-CCO could also subsume classes and not just object properties. 

Assuming that works, should we release PROV-CCO without the (PROV-BFO) imports? Importing in this context is only needed for checking consistency during development, right?

**Comment by johnbeve** [comment]
@tmprd CCO is so intimately intwined with BFO, I'm having trouble seeing how you'd release PROV-CCO without the PROV-BFO imports. BFO is a proper part of CCO. 

I think I must be misunderstanding what you're asking...

**Comment by tmprd** [comment]
> @tmprd CCO is so intimately intwined with BFO, I'm having trouble seeing how you'd release PROV-CCO without the PROV-BFO imports. BFO is a proper part of CCO.
> 
> I think I must be misunderstanding what you're asking...

Sounds good to me! I wasn't sure how modular it needs to be, but these extensions are so small it makes little difference to import them. I noticed that the [PROV-DC mapping](https://www.w3.org/ns/prov-dc-directmappings) has two related extensions [here](http://www.w3.org/ns/prov-dc) and [here](https://www.w3.org/ns/prov-dc-refinements) but these aren't imported, only related by [frbr:complement](https://vocab.org/frbr/core#term-complement).

Maybe we can change the namespace of PROV-BFO to https://raw.githubusercontent.com/BFO-Mappings/BFO-Mappings/main/PROV/prov-bfo-directmappings.ttl so that PROV-CCO can import it from the web.

**Pull request merged**
